---
- hosts: dev
  become: True

  tasks:
  - name: install python pip
    yum:
      name: python-pip
      state: present

  - name: install docker-py python module
    pip:
      name: docker-py
      state: present

  - name: install docker
    yum:
      name: docker
      state: present

  - name: start docker
    service:
       name: docker
       state: started
       enabled: yes

  - name: start the docker container
    docker_container:
       name: springboot
       image: "pratimadewde/docker_jenkins_springboot:${BUILD_NUMBER}"
       state: started
       published_ports: 
         - 0.0.0.0:8081:8080
